# Generated by Django 4.1.2 on 2022-10-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='FollowersCount',
        ),
    ]
